alpha-blog/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to:'pages#about'
  
  resources :articles, :users#, only: [:show, :index, :new, :create, :edit, :update]
  
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
  
  
end

alpha-blog/app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Tavo Molina", "www.github.com/tavo-molina", class: "text-white" %></small>
  </div>
</footer>

alpha-blog/app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
  <%if name == "notice"%>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
      
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <%else%>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= msg %>
      
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <%end%>
  <% end %> 
</div> 

alpha-blog/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      </li>
      <li class="nav-item">
      <%= link_to 'Bloggers', users_path, class:"nav-link" %>

      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
          <%= link_to 'Create new article', new_article_path, class: 'dropdown-item' %>
          <% end%>
          <%= link_to 'View articles', articles_path, class: 'dropdown-item' %>
        </div>
      </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in? && current_user.admin? %>
            <%= link_to 'Create new category', new_category_path, class: 'dropdown-item' %>
            <% end%>
            <%= link_to 'View categories', categories_path, class: 'dropdown-item' %>
          </div>
        </li>
        <% if logged_in?%>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= "(Admin) " if current_user.admin? %> Profile [<%=current_user.username%>]
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'View your profile', user_path(current_user), class: 'dropdown-item' %>
              <%= link_to 'Edit your profile', edit_user_path(current_user), class: 'dropdown-item' %>
              <%= link_to 'Delete your profile', user_path(current_user), class: 'dropdown-item text-danger', method: :delete, data: { confirm: "Are you sure?" } %>
            </div>
          </li>
        <li class="nav-item">
          <%= link_to 'Log out', logout_path, class: 'nav-link', method: :delete  %>
        </li>
        <% else%>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: 'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: 'nav-link'  %>
        </li>
        <% end%>
        
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

alpha-blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  <%= render 'layouts/footer' %>
  </body>
</html>