alpha-blog/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to:'pages#about'
  
  resources :articles, :users#, only: [:show, :index, :new, :create, :edit, :update]
  
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
  
  
end

alpha-blog/app/models/category.rb
class Category < ApplicationRecord
    
    validates :name, presence: true, length: {minimum: 3, maximum:25}
    validates_uniqueness_of :name
    has_many :article_categories
    has_many :articles, through: :article_categories
end

alpha-blog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    before_action :require_admin, except: [:index, :show]

    def new
        @category = Category.new()
    end

    def index
        @categories = Category.paginate(page: params[:page], per_page:5)
    end

    def show
        @category = Category.find(params[:id])
        @articles = @category.articles.paginate(page: params[:page], per_page: 5 )

    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category created succesfully"
            redirect_to @category
        else
            render 'new'
        end
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice] = "Category name updated succesfully"
            redirect_to @category
        else
            render 'edit'
        end
        
    end

    private

    def category_params
        params.require(:category).permit(:name)
    end
    
    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Only admins can perform that action!"
            redirect_to categories_path
        end
    end

end

alpha-blog/app/views/categories/_category.html.erb
<%=link_to category.name, category_path(category), class: "badge badge-pill badge-info mr-1" %>

alpha-blog/app/views/categories/_form.html.erb
<% if @category.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">The following errors prevented the User from being saved</h4>
        <ul>
        <% @category.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %> 
      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name,"Category name", class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>

alpha-blog/app/views/categories/edit.html.erb
<h1 class="text-center mt-4"> Edit the category </h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
 <% #render 'shared/errors', obj: @user %>
 <!----  check errors here-->
 <%= render 'form' %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div> 

alpha-blog/app/views/categories/index.html.erb
  <h1 class="text-center mt-4">Listing all articles</h1>

<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
              <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
            edited <%= time_ago_in_words(category.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div> 


<div class="flickr_pagination mb-4">
  <%= will_paginate @categories, :container => false %>
</div> 

alpha-blog/app/views/categories/new.html.erb
<h1 class="text-center mt-4"> Create a new category </h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
 <% #render 'shared/errors', obj: @user %>
 <!----  check errors here-->
 <% if @category.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">The following errors prevented the User from being saved</h4>
        <ul>
        <% @category.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %> 
      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name,"Category name", class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div> 

alpha-blog/app/views/categories/show.html.erb
<h1 class="text-center mt-4" >Category <%= @category.name%> </h1>

<% if  logged_in?  && current_user.admin?%>
<div class="text-center mt-4" >
    <%= link_to "Edit category", edit_category_path(@category), class:"btn btn-outline-info" %>
</div>
<% end %>

<h3 class="text-center mt-4"> Articles  </h3>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article'%>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div> 